// ---------------------------------------------------------------------------
// The RAG core: embed the knowledge base once (cached), embed the incoming
// question, rank chunks by cosine similarity, return the top matches.
// ---------------------------------------------------------------------------

import { GoogleGenAI } from "@google/genai";
import { KNOWLEDGE, type Chunk } from "./knowledge";
import precomputed from "./embeddings.json";

// Precomputed KB embeddings (generated by `npm run embed`). Lets the deployed
// site skip re-embedding the whole knowledge base on every cold start.
const preMap = new Map(
  (precomputed as { id: string; vector: number[] }[]).map((p) => [p.id, p.vector])
);

const EMBED_MODEL = "gemini-embedding-001";
export const CHAT_MODEL = "gemini-flash-latest";

let ai: GoogleGenAI | null = null;

export function getClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is not set. Add it to .env.local (get a free key at https://aistudio.google.com/apikey)."
    );
  }
  if (!ai) ai = new GoogleGenAI({ apiKey });
  return ai;
}

async function embed(text: string): Promise<number[]> {
  const res = await getClient().models.embedContent({
    model: EMBED_MODEL,
    contents: text,
  });
  const values = res.embeddings?.[0]?.values;
  if (!values) throw new Error("Embedding failed — no vector returned.");
  return values;
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

// Embed the whole knowledge base once and keep it in module memory. On a
// serverless platform this persists for the life of the warm instance, so
// repeat requests skip the embedding cost entirely.
type Indexed = Chunk & { vector: number[] };
let indexPromise: Promise<Indexed[]> | null = null;

function buildIndex(): Promise<Indexed[]> {
  if (!indexPromise) {
    indexPromise = (async () => {
      const indexed: Indexed[] = [];
      for (const chunk of KNOWLEDGE) {
        // Use the precomputed vector when available; only embed at runtime for
        // chunks added since the last `npm run embed`.
        const vector =
          preMap.get(chunk.id) ?? (await embed(`${chunk.title}\n${chunk.content}`));
        indexed.push({ ...chunk, vector });
      }
      return indexed;
    })().catch((err) => {
      // Reset so a transient failure (e.g. missing key on cold start) can retry.
      indexPromise = null;
      throw err;
    });
  }
  return indexPromise;
}

export type RetrievedChunk = Chunk & { score: number };

export async function retrieve(query: string, topK = 4): Promise<RetrievedChunk[]> {
  const index = await buildIndex();
  const queryVec = await embed(query);
  return index
    .map(({ vector, ...chunk }) => ({ ...chunk, score: cosineSimilarity(queryVec, vector) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, topK);
}
